import type { Metadata } from 'next';
import { Unna } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

const unna = Unna({
  variable: '--font-unna',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const hestia = localFont({
  src: [{ path: '/fonts/Hestia-Regular.ttf' }],
  variable: '--font-hestia',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${unna.variable} ${hestia.variable} antialiased`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
