import type { Metadata } from 'next';
import { Unna } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/Navbar';

const unna = Unna({
  variable: '--font-unna',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const difont = localFont({
  src: [{ path: '/fonts/difont.ttf' }],
  variable: '--font-difont',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${unna.variable} ${difont.variable} antialiased`}>
        <ThemeProvider>
          <div className="relative">
            <Navbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
